# Generated by Django 6.0.5 on 2026-05-10 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appvenda', '0004_produto_lote_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Appvenda.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='lote',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
