# Generated by Django 6.0.5 on 2026-05-13 21:09

import Appvenda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appvenda', '0007_category_client_img_product_remove_produto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default=Appvenda.models.set_default_category, max_length=100, unique=True),
        ),
    ]
