# Generated by Django 6.0.5 on 2026-05-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appvenda', '0008_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/default.jpg', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lot',
            field=models.CharField(default='1981', max_length=100),
        ),
        migrations.DeleteModel(
            name='Img_product',
        ),
    ]
